name: Update Leaderboard and Merge PR

on:
  pull_request:
    branches:
      - main

jobs:
  update-leaderboard:
    name: Update Leaderboard
    runs-on: ubuntu-latest

    steps:
    # Checkout the PR code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install dependencies (optional)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No requirements file found"

    # Run the leaderboard update script
    - name: Update Leaderboard
      run: python scripts/update_leaderboard.py

    # Commit and push updated leaderboard if there are changes
    - name: Commit and Push Leaderboard
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add LEADERBOARD.md progress.json
        git commit -m "Update leaderboard [auto]" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    name: Auto Merge Pull Request
    runs-on: ubuntu-latest
    needs: update-leaderboard

    steps:
    # Automatically merge the PR
    - name: Merge Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const prNumber = context.payload.pull_request.number;

          await github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
            merge_method: "squash",
          });
